SPOTIPY_CLIENT_ID='ea602897ce274a288bab779163c78ab7'

SPOTIPY_CLIENT_SECRET='aec202ae7fa940b8892a5770e6ee65f2'

SPOTIPY_REDIRECT_URI='http://localhost:9000'

cids = {
    "16":"Japan", # japan
    "13": "Netherlands", # netherlands
    "17": "New Zealand", # new zeland
    "19": "Norway", # norway
    "20": "Portugal", # portugal
    "4": "Australia", # australia
    "6": "Austria", # austria
    "7": "Belgium", # belgium
    "8": "Brazil", # brazil
    "49":"Bulgaria", # bulgaria
    "9": "canada", # canada
    "37": "Chile", # chile
    "42": "China", # china
    "32": "Denmark", # denmark
    "10": "Finland", # finland
    "11": "France", # france
    '12': "German", # germany
    "2": "Greece", # greece
    "43": "India", # india
    "15": "Ireland", # ireland
    "18": "Italy", # italy
    "21": "Spain", # spain
    "22": "Sweden", # sweden
    "23": "Switzerland", # switzerland
    "14": "Taiwan", # taiwan
    "25": "UK Singles", # uk
    "27": "USA Singles" # usa
}

country_artist_map = {
    "nan":'Dont know',
            'BR' :'Brasil',
    'Mato Grosso do Sul'  :'Brasil',
    'GoiÃ\x83Â\x83Ã\x82Â¢nia' : 'Dont know',
    'US' : 'USA',
    'MX' :'Mexico',
    'GB': 'United Kingdom',
 'KR' : 'South Korea',
 'Seattle' :'USA',
 'CO' :'Columbia',
 'England' :'United Kingdom',
 'CA' : 'Canada', 
 'GR' :'Greece',
 'PR': 'Puerto Rico',
  'Las Palmas de Gran Canaria': 'Spain',
 'JP' : 'Japan',
 'SE' :'Sweden', 
 'NL' :'Netherlands',
 'BG' : 'Bulgaria',
 'RU' : 'Rumunia',
 'DE': 'Germany',
   'FR' : 'France',
 'Berlin' : 'Germany',
 'ES' : 'Spain',
   'AR' : 'Argentina',
   'Sevilla' : 'Spain',
   'Madrid': 'Spain',
 'PT' : 'Portugal',
   'Malabo' :'Guinea-Bissau',
   'ST' : 'Sao Tome and Principe',
   'CabreÃ\x83Â\x83Ã\x82Âºva'  : 'Dont know',
   'IT': 'Italy',
     'AU' : 'Australia',
   'Scotland' : 'United Kingdom',
   'DK': 'Denmark',
 'Kent' : 'United Kingdom',
 'QuÃ\x83Â\x83Ã\x82Â©bec' : 'Canada',
 'IE' : 'Ireland',
 'BE': 'Belgium',
   'NO' : 'Norway',
 'Oslo' : 'Norway',
 'FI': 'Finland', 
 'JyvÃ\x83Â\x83Ã\x82Â¤skylÃ\x83Â\x83Ã\x82Â¤' : 'Dont know',
 'Barcelona' : 'Spain',
 'Gothenburg' : 'Sweden',
 'Stockholm' : 'Sweden',
 'Helsinki' : 'Finland',
 'Santiago' : 'Chile',
   'CL' : 'Chile',
 'NG': 'Nigeria',
   'DZ' : 'Algieria',
 'Milano' : 'Italy',
   'AT' : 'Austria',
   'Florida' : 'USA',
 'Lisboa' : 'Portugal',
   'RO': 'Romania',
   'Beograd' : 'Serbia',
   'McAllen' : 'USA',
   'BB' : 'Barbados',
   'Hamburg' : 'Germany',
   'Detroit': 'USA',
     'XK': 'Kosowo',
 'Manchester' : 'United Kingdom',
 'JM' : 'Jamaica',
 'Dresden' : 'Germany',
 'CH' : 'Switzerland',
 'London' : 'United Kingdom',
 'MQ' : 'Martinique',
 'Napoli' : 'Italy',
 'Leeds' :'United Kingdom',
 'Bergen': 'Norway',
 'Amsterdam': 'Netherlands',
   'Nashville' :'USA',
 'Atlanta':'USA',
   'Oppland' :'Norway',
   'SI' : 'Slovenia',
 'Paris': 'France',
   'IL': 'Israel',
   'RS' : 'Serbia',
   'AL': 'Albania',
 'HR' : 'Croatia',
 'Copenhagen': 'Denmark',
   'AM' : 'Armenia',
   'TR' :'Turkey',
 'Sheffield': 'United Kingdom',
   'TW' : 'Taiwan',
     'MK': 'North Macedonia',
       'Philadelphia' : 'USA',
     'IN': 'India',
 'DÃ\x83Â\x83Ã\x82Â¼sseldorf' : 'Germany',
   'York': 'United Kingdom',
     'Washington, D.C.' : 'USA',
   'Darmstadt' : 'Germany',
 'Punjab':'India',
   'Neuss': 'Germany',
     'Roma' :'Italy',
 'Ithaca' : 'USA',
 'Melbourne': 'Australia',
   'Courbevoie':'France',
     'Athens':'Greece',
       'AO':'Angola',
 'New York':"USA",
   'GL':'Geenland',
     'Buenos Aires' : 'Argentina',
 'HU':'Hungary',
   'NZ': 'New Zeland',
     'Navarra':'Spain',
       'SK':'Slovakia',
         'Amazonas':'Brasil',
 'Monroe':'USA',
   'CY':'Cyprus',
     'Los Angeles':'USA',
       'St. Gallen':'Switzerland',
       'Lambeth':'United Kingdom',
         'VE':'Venezuela',
           'Orange County':'USA',
 'DO':'Dominican Republic',
   'Brisbane':'Australia',
     'Hawaii':'USA',
       'NÃ\x83Â\x83Ã\x82Â¼rnberg':'Germany',
 'Ciudad de MÃ\x83Â\x83Ã\x82Â©xico': 'Mexico',
   'IS':'Iceland', 
   'Nottingham':'United Kingdom' ,
   'Milwaukee':'USA',
 'Vellinge Municipality' :'Sweden',
 'PG' :'Papua New Guinea',
 'Herzogenaurach' :'Germany',
 'XE' :'Dont know',
 'GH':'Ghana',
   'UA' :'Ukraine',
 'Inglewood':'USA',
 'Burgas' :'Bulgaria',
 'Illinois':'USA',
   'Brooklyn' :'USA',
 'BA' :'Bosnia and Herzegovina',
 'Croydon':'United Kingdom',
   'Turku':'Finland',
     'Marseille':"France",
       'KZ':'Kazakhstan',
 'Miami':'USA',
   'JÃ\x83Â\x83Ã\x82Â¶nkÃ\x83Â\x83Ã\x82Â¶ping': 'Dont know',
     'Oulu': 'Finland',
       'Istanbul':'Turkey',
 'PA' :'Panama',
 'Sevran' :'France',
 'Rio Grande do Sul' :'Brasil',
 'Torrance' :'USA',
 'Andebu':'Norway',
   'LT':'Lithuania',
 'Nordrhein-Westfalen':'Germany',
   'PL' :'Poland',
 'Chicago':'USA',
   'Budapest':'Hungary',
   'SG' :'Singapore',
   'Sankt-Peterburg':'Russia',
 'Tennessee':'USA',
   'Rio de Janeiro':'Brasil',
   'Bremen':'Germany',
     'Boston':'USA',
       'Burlington':'Canada',
 'BucureÃ\x83Â\x88Ã\x82Â\x99ti':'Romania',
   'Berkeley' :'USA',
 'ZA' :'South Africa',
 'Scarborough' :'United Kingdom',
 'Wiesbaden':'Germany',
 'Dublin':'Ireland',
   'Bonn' :'Germany',
 'Celle' :'Germany',
 'Baltimore' :'USA',
 'Viareggio' :'Italy',
 'Elche' : 'Spain',
 'Liverpool':'United Kingdom',
 'Albertslund':' Denmark',
   'Warsaw':'Poland',
     'West Yorkshire': 'United Kingdom',
   'Salt Lake City' :'USA',
   'Gabrovo':'Bulgaria',
 'Salzburg' :'Austria',
 'La Habana':'Cuba',
   'Oakland':'USA', 
 'Perth' :'Australia',
 'Tokushima':'Japan',
   'AG':'Antigua and Barbuda',
   'Belfast':'United Kingdom',
   'GY':'	Guyana',
 'Bristol':'United Kingdom',
   'Las Vegas' :'USA',
   'Catalunya':'Spain',
   'Mainz' :'Germany',
   'North Carolina':'USA',
     'Guyancourt':'France',
 'Bellante' :'Italy',
 'Lodi':'USA',
 'Birmingham':'United Kingdom',
   'Kilkenny' :'Ireland',
   'ID' :'Indonesia',
   'Minsk' :'Belarus',
   'CD' :'Congo',
   'Thal':'Austria',
 'Groningen':'Nethrlands',
   'BQ' :'Bonaire, Sint Eustatius and Saba',
   'Sintra':'Portugal',
   'Glasgow' :'United Kingdom',
   'Hanau':'Germany',
     'Barbate':'Spain',
     'Hackney':'United Kingdom',
       'MD':'	Moldova',
 'Sydney':'Australia',
   'Scunthorpe' :'United Kingdom',
 'SÃ\x83Â\x83Ã\x82Â£o Paulo':'Brasil',
   'MY':'Malaysia',
 'CorrÃ\x83Â\x83Ã\x82Â¨ze' :'Dont know',
 'Choisy-le-Roi' :'France',
 'Auckland' :'New Zeland',
 'Coventry':'United Kingdom',
 'Jersey City' :'USA',
 'UY':'Uruguay',
   'Rovigo' :'Italy',
 'Amersfoort':'Netherlands',
   'Asheville':'USA',
   'Bielefeld':'Germany',
   'Taipei':'Taiwan',
 'Hove':'United Kingdom',
   'Castlemaine' :'Australia',
 'Pernambuco' :'Brasil',
 'GenÃ\x83Â\x83Ã\x82Â¨ve' :'Switzerland',
 'Oxford':'United Kingdom',
 'Watford' :'United Kingdom',
 'Tenerife':'Spain',
   'The Hague' :'Netherlands',
 'Australian Capital Territory' :'Australia',
 'CI':"Côte d'Ivoire",
 'VÃ\x83Â\x83Ã\x82Â¤stervik' :'Sweden',
 'Kingdom of the Netherlands' :'Netherlands',
 'Saint John':'Canada',
 'CZ':'Czech Republic',
   'Colorado':'USA',
   'NykÃ\x83Â\x83Ã\x82Â¶ping' :'Sweden',
 'Wien' :'Austria',
 'Saddle River':'USA',
 'Jacksonville' :'USA',
 'Villajoyosa / La Vila Joiosa':'Spain',
   'CU':'Cuba',
     'Sofia':'Bulgaria',
 'Bad VÃ\x83Â\x83Ã\x82Â¶slau' :'Dont know',
 'Ann Arbor':'USA',
 'Thessaloniki':'Greece',
   'Moscow':'Russia',
     'GT':'Guatemala',
 'Gelsenkirchen':'Germany',
   'VG' :'British Virgin Islands',
 'Indianapolis':'USA',
   'Texas':'USA',
     'Verona':'Italy',
   'MA' :'Morocco',
   'Arizona':'USA',
 'Giessen':'Germany',
   'Dingle':'Ireland',
     'SN' :'Senegal',
     'TH' :'Thailand',
     'Chorley' :'United Kingdom',
 'Lagos' :'Portugal',
 'Mazatlan':'Mexico',
   'Enschede':'Netherlands',
 'ParanÃ\x83Â\x83Ã\x82Â¡':'Dont know',
   'New South Wales' :'Australia',
 'ZÃ\x83Â\x83Ã\x82Â¼rich':'Switzerland',
 'Ratingen' :'Germany',
 'Cali' :'Columbia',
 'Toronto':'Canada',
   'Austin' :'USA',
 'EE':'Estonia',
   'Houston':'USA',
   'LV':'Latvia',
   'Portland':'USA',
 'Cleveland' :'USA',
 'Linz':"Austria",
   'Bradford' :'United Kingdom',
 'Luzern':'Switzerland',
   'Ferrara':'Italy',
   'Palmerston North':'New Zleand',
 'Vilnius':'Lithuania',
   'BF' :'Burkina Faso',
   'Mudgee' :'Australia',
   'OberÃ\x83Â\x83Ã\x82Â¶sterreich' :'Austria',
 'Phoenix':'USA',
 'OstrÃ\x83Â\x83Ã\x82Â³w Wielkopolski':'Poland',
   'Wellington':'New Zeland',
     'PH' :'Philippines',
   'Porto':'Portugal',
 'Eskilstuna Municipality':'Sweden',
   'Nova Scotia':'Canada',
   'Rebstein':'Switzerland',
     'Hamilton':'Canada',
     'Tilburg':'Netherlands',
 'Monterrey': 'Mexico',
   'KÃ\x83Â\x83Ã\x82Â¶ln' :'Germany',
 'Northern Ireland':'United Kingdom',
 'SaarbrÃ\x83Â\x83Ã\x82Â¼cken' :'Germany',
 'VC':'	Saint Vincent and Grenadines',
   'Vancouver':'Canada',
     'LuleÃ\x83Â\x83Ã\x82Â¥':'Sweden',
 'Matosinhos':'Portugal',
   'Eindhoven' :'Netherlands',
 'LiepÃ\x83Â\x84Ã\x82Â\x81ja':'Lotva',
 'ReykjavÃ\x83Â\x83Ã\x82Â\xadk' :'Icelnd',
 'MT':'Malta',
   'California' :'USA', 
   'GP' :'Guadeloupe',
   'Burnley' :'United Kingdom',
 'Pittsburgh':'USA',
   'Wales' :'United Kingdom',
 'HK' :'Hong Kong',
 'Devon':'United Kingdom',
   'Nijmegen' :'Netherlands',
   'Edinburgh':'United Kingdom',
   'CN': 'China',
   'Brighton':'United Kingdom',
   'MM': 'Birma',
   'Columbus': 'USA',
   'Memphis': 'USA',
   'St. Louis': 'USA',
   'Osaka': 'Japan',
   'Hendersonville': 'USA',
   'Temecula': 'USA',
   'Hoboken': 'USA',
   'Tampa':'USA',
   'Orange': 'France',
   'BO': 'Bolivia',
   'Hollywood': 'USA',
   'Queensbridge':'USA',
   'BS': 'Bahamas',
   'Pretoria': 'RPA',
   'German': 'Germany',
   'USA Singles': 'USA',
   'UK Singles': 'UK'
}